---
title: "Isotope Chronology"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}
```

# Data
## Isotopes
```{r}
sst_raw  <- read_csv(here("data","raw", "zukovica_isotope.csv"), show_col_types = FALSE) |> 
  mutate(excavation_unit = factor(excavation_unit, levels = c(
          124,
          122,
          121,
          119,
          116, 115,
          113.5, #Dated
          114,#Dated by interpolation
          118, #Dated by interpolation
          113,#Dated
          108, 112, 25,#Dated
          111, 24,#Dated
          23, 
          110,
          22, 
          109,
          107,20,
          19,
          106,
          17,
          105,
          16
        )),
          order=c(1,
                  2,
                  3,
                  4,
                  5,5,
                  6,
                  7,
                  8,
                  9,
                  10,10,10,
                  11,11,
                  12,
                  13,
                  14,
                  15,
                  16,16,
                  17,
                  18,
                  19,
                  20,21)) |> 
  arrange(excavation_unit)
  

```
## Chronology
```{r}
Dates <- 

```


# Plot
```{r}

sst_raw |> 
  ggplot()+
  aes(x=order,y=d18O_max_winter)+
  geom_point()


```

